use std::fmt;

#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum Keyword {
    Program,
    Var,
    Let,
    Function,
    Procedure,
    Begin,
    End,
    Uses,
    Type,
    Record,
    Class,
    Case,
    If,
    While,
    Then,
    Else,
    Nil,
    For,
    To,
    Do,
    Unit,
    Interface,
    Implementation,
    Initialization,
    Finalization,
    Array,
    Of,
    Const,
    Out,
    True,
    False,
    Set,
    Try,
    Except,
    Finally,
    Raise,
    With,
    Exit,
    Export,
    Variant,
}

impl Keyword {
    fn try_parse_lowercase(from: &str) -> Option<Self> {
        match from {
            "program" => Some(Keyword::Program),
            "let" => Some(Keyword::Let),
            "var" => Some(Keyword::Var),
            "function" => Some(Keyword::Function),
            "procedure" => Some(Keyword::Procedure),
            "begin" => Some(Keyword::Begin),
            "end" => Some(Keyword::End),
            "uses" => Some(Keyword::Uses),
            "type" => Some(Keyword::Type),
            "class" => Some(Keyword::Class),
            "record" => Some(Keyword::Record),
            "case" => Some(Keyword::Case),
            "if" => Some(Keyword::If),
            "while" => Some(Keyword::While),
            "then" => Some(Keyword::Then),
            "else" => Some(Keyword::Else),
            "nil" => Some(Keyword::Nil),
            "for" => Some(Keyword::For),
            "to" => Some(Keyword::To),
            "do" => Some(Keyword::Do),
            "unit" => Some(Keyword::Unit),
            "interface" => Some(Keyword::Interface),
            "implementation" => Some(Keyword::Implementation),
            "initialization" => Some(Keyword::Initialization),
            "finalization" => Some(Keyword::Finalization),
            "array" => Some(Keyword::Array),
            "of" => Some(Keyword::Of),
            "const" => Some(Keyword::Const),
            "out" => Some(Keyword::Out),
            "true" => Some(Keyword::True),
            "false" => Some(Keyword::False),
            "set" => Some(Keyword::Set),
            "try" => Some(Keyword::Try),
            "except" => Some(Keyword::Except),
            "finally" => Some(Keyword::Finally),
            "raise" => Some(Keyword::Raise),
            "with" => Some(Keyword::With),
            "exit" => Some(Keyword::Exit),
            "export" => Some(Keyword::Export),
            "variant" => Some(Keyword::Variant),
            _ => None,
        }
    }

    pub fn try_parse(from: &str, case_sensitive: bool) -> Option<Self> {
        if case_sensitive {
            Self::try_parse_lowercase(from)
        } else {
            Self::try_parse_lowercase(&from.to_ascii_lowercase())
        }
    }
}

impl fmt::Display for Keyword {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str(match self {
            Keyword::Program => "program",
            Keyword::Var => "var",
            Keyword::Let => "let",
            Keyword::Function => "function",
            Keyword::Procedure => "procedure",
            Keyword::Begin => "begin",
            Keyword::End => "end",
            Keyword::Uses => "uses",
            Keyword::Type => "type",
            Keyword::Class => "class",
            Keyword::Record => "record",
            Keyword::If => "if",
            Keyword::Case => "case",
            Keyword::While => "while",
            Keyword::Then => "then",
            Keyword::Else => "else",
            Keyword::Nil => "nil",
            Keyword::For => "for",
            Keyword::To => "to",
            Keyword::Do => "do",
            Keyword::Unit => "unit",
            Keyword::Interface => "interface",
            Keyword::Implementation => "implementation",
            Keyword::Initialization => "initialization",
            Keyword::Finalization => "finalization",
            Keyword::Array => "array",
            Keyword::Of => "of",
            Keyword::Const => "const",
            Keyword::Out => "out",
            Keyword::True => "true",
            Keyword::False => "false",
            Keyword::Set => "set",
            Keyword::Try => "try",
            Keyword::Except => "except",
            Keyword::Finally => "finally",
            Keyword::Raise => "raise",
            Keyword::With => "with",
            Keyword::Exit => "exit",
            Keyword::Export => "export",
            Keyword::Variant => "variant",
        })
    }
}
